baseURL = 'https://thenickvendetta.github.io/'
publishDir = 'docs'
languageCode = 'en-us'
title = 'Nick Vendetta | Home'
theme = 'PaperMod'

# Kekalkan canonifyURLs tapi BUANG relativeURLs
canonifyURLs = true

[params]
    env = 'production'
    title = 'Nick @ Infosec'
    description = 'Pentest Write-ups & Network Auditing Lab'
    defaultTheme = 'dark'
    disableThemeToggle = true
    
    # Tambah baris ni untuk fix CSS
    assets = { disableFingerprinting = true }

    [params.profileMode]
        enabled = true
        title = "Hi, I'm Nick"
        subtitle = "Final Year Computer Networking Student & IT Intern. Focusing on Offensive Security & Penetration Testing."
        imageUrl = "https://github.com/thenickvendetta.png"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/thenickvendetta"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/nikmuhammadasyraf"

[[menu.main]]
    name = "Portfolio"
    url = "/posts/"
    weight = 10

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20

[[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 30